### ISSUE TITLE
Especificação do Projeto - Definição de Personas e História de usuários

### ISSUE THREAD

**Issue by felipesobrinho** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e3-proj-mov-t1-CardAppio#4]
Links Úteis:
- Personas:
[Persona: o que é, como definir](https://resultadosdigitais.com.br/marketing/persona-o-que-e/)
[Persona e público-alvo: qual a diferença no marketing?](https://flammo.com.br/blog/persona-e-publico-alvo-qual-a-diferenca/)

- História de usuários: 
[Histórias de usuários com exemplos e um template](https://www.atlassian.com/br/agile/project-management/user-stories)
[Como escrever boas histórias de usuário (User Stories)](https://medium.com/vertice/como-escrever-boas-users-stories-hist%C3%B3rias-de-usu%C3%A1rios-b29c75043fac)
[User Stories - Descrição de requisitos que humanos entendem](https://www.luiztools.com.br/post/user-stories-descricao-de-requisitos-que-humanos-entendem/)
[9 Common User Story Mistakes Most Product Managers Make](https://www.reqview.com/doc/user-stories-example/)

**Comment by ClaudioBarroso** [comment]
Feito!
